version: "3.7"
services:
  home:
    build:
      context: ./home
    ports:
      - 8080:8080
    volumes:
      - ./home:/project
      - /project/node_modules
  strapi: 
    build:
      context: ./general/strapi
    ports: 
      - 1337:1337
  general: 
    build: 
      context: ./general
    ports: 
      - 8081:3000