services:
  fibo-strapi:
    environment:
      - ONTPUB_FAMILY=fibo
      - PRODUCT=htmlpages
      - BRANCH_NAME=develop
      - TAG_NAME=latest
    build:
      context: ./general/strapi
      args:
        - ONTPUB_FAMILY=fibo
        - PRODUCT=htmlpages
        - BRANCH_NAME=develop
        - TAG_NAME=latest
    volumes:
      - ./general/strapi:/strapi
      - opt:/opt
  fibo-pages:
    environment:
      - ONTPUB_FAMILY=fibo
      - PRODUCT=htmlpages
      - BRANCH_NAME=develop
      - TAG_NAME=latest
      - STRAPI_URL=http://fibo-strapi:1337
    build:
      context: ./general
      args:
        - ONTPUB_FAMILY=fibo
        - PRODUCT=htmlpages
        - BRANCH_NAME=develop
        - TAG_NAME=latest
        - STRAPI_URL=http://fibo-strapi:1337
    volumes:
      - opt:/opt
    depends_on:
      - fibo-strapi
  nginx:
    environment:
      - PRODUCT=htmlpages
      - BRANCH_NAME=develop
      - TAG_NAME=latest
    build:
      context: ./home
      args:
        - PRODUCT=htmlpages
        - BRANCH_NAME=develop
        - TAG_NAME=latest
    volumes:
      - ./general/strapi:/strapi
      - opt:/opt
    depends_on:
      - fibo-strapi
      - fibo-pages
    ports:
      - 8080:80

volumes:
  opt:
