services:
  fibo-strapi:
    image: edmcouncil/fibo-strapi
    build:
      context: ./general/strapi
      args:
        - ONTPUB_FAMILY=fibo
        - BRANCH_NAME=develop
        - TAG_NAME=latest
    volumes:
      - ./general/strapi/db:/strapi
      - opt:/opt
  fibo-pages:
    image: edmcouncil/fibo-pages
    build:
      context: ./general
      args:
        - ONTPUB_FAMILY=fibo
        - BRANCH_NAME=develop
        - TAG_NAME=latest
    environment:
      - STRAPI_URL=http://fibo-strapi:1337
    volumes:
      - opt:/opt
    depends_on:
      - fibo-strapi
  spec:
    image: edmcouncil/spec
    build:
      context: ./home
    environment:
      - FAMILY_REGEX=fibo
    volumes:
      - opt:/opt
    depends_on:
      - fibo-strapi
      - fibo-pages
    ports:
      - 8080:80

volumes:
  opt:
