name: publish_docker_image

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: edmcouncil/html-pages
      -
        name: Build and push edmcouncil/fibo-strapi:${{ steps.meta.outputs.version }}
        uses: docker/build-push-action@v5
        with:
          context: ./general/strapi
          push: true
          tags: edmcouncil/fibo-strapi:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ONTPUB_FAMILY=fibo
            BRANCH_NAME=${{ steps.meta.outputs.version }}
      -
        name: Build and push edmcouncil/fibo-pages:${{ steps.meta.outputs.version }}
        uses: docker/build-push-action@v5
        with:
          context: ./general
          push: true
          tags: edmcouncil/fibo-pages:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ONTPUB_FAMILY=fibo
            BRANCH_NAME=${{ steps.meta.outputs.version }}
      -
        name: Build and push edmcouncil/spec:${{ steps.meta.outputs.version }}
        uses: docker/build-push-action@v5
        with:
          context: ./home
          push: true
          tags: edmcouncil/spec:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
